<?xml version="1.0" ?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

	<xacro:include filename="$(find robotont_description)/xacro/roller.urdf.xacro"/>
	<!-- Roller positioning -->
	<xacro:property name="roller_radial_dist" value="0.0255" />
	<xacro:property name="roller_z_distance" value="0.008" />
	<xacro:property name="roller_init_angle" value="${pi/14}" />

	<xacro:macro
		name="rim_macro"
		params="name color angle wheel_distance wheel_center_height"
	>

		<link name="rim_${name}_link">

			<inertial>

				<origin xyz="0 0 -0.000343"/>
				<mass value="0.00835758"/>
				<inertia
					ixx="6.63684e-07"
					ixy="0"
					ixz="0"
					iyy="6.63684e-07"
					iyz="0"
					izz="9.40333e-07"
				/>

			</inertial>
			<visual>

				<geometry>

					<mesh scale="0.001 0.001 0.001" filename="package://robotont_description/meshes/rim.stl"/>

				</geometry>
				<material name="rim_${name}_material">

					<color rgba="${color} 1"/>

				</material>

			</visual>
			<collision>

				<geometry>

					<mesh scale="0.001 0.001 0.001" filename="package://robotont_description/meshes/rim.stl"/>

				</geometry>

			</collision>

		</link>
		<joint
			name="rim_${name}_joint"
			type="continuous"
		>

			<parent link="base_link" />
			<child link="rim_${name}_link" />
			<axis xyz="0 1 0"/>
			<origin
				xyz="${wheel_distance*sin(angle)} ${wheel_center_height} ${wheel_distance*cos(angle)}"
				rpy="${pi/2} ${angle+pi} 0"
			/>

		</joint>
		<!-- Front rollers -->
		<xacro:roller_macro
			parent="${name}"
			radial_dist="${roller_radial_dist}"
			z_distance="${roller_z_distance}"
			z_distance_reflect="-1"
			init_angle="${roller_init_angle}"
			no_of_roller="0"
		/>
		<xacro:roller_macro
			parent="${name}"
			radial_dist="${roller_radial_dist}"
			z_distance="${roller_z_distance}"
			z_distance_reflect="-1"
			init_angle="${roller_init_angle}"
			no_of_roller="1"
		/>
		<xacro:roller_macro
			parent="${name}"
			radial_dist="${roller_radial_dist}"
			z_distance="${roller_z_distance}"
			z_distance_reflect="-1"
			init_angle="${roller_init_angle}"
			no_of_roller="2"
		/>
		<xacro:roller_macro
			parent="${name}"
			radial_dist="${roller_radial_dist}"
			z_distance="${roller_z_distance}"
			z_distance_reflect="-1"
			init_angle="${roller_init_angle}"
			no_of_roller="3"
		/>
		<xacro:roller_macro
			parent="${name}"
			radial_dist="${roller_radial_dist}"
			z_distance="${roller_z_distance}"
			z_distance_reflect="-1"
			init_angle="${roller_init_angle}"
			no_of_roller="4"
		/>
		<xacro:roller_macro
			parent="${name}"
			radial_dist="${roller_radial_dist}"
			z_distance="${roller_z_distance}"
			z_distance_reflect="-1"
			init_angle="${roller_init_angle}"
			no_of_roller="5"
		/>
		<xacro:roller_macro
			parent="${name}"
			radial_dist="${roller_radial_dist}"
			z_distance="${roller_z_distance}"
			z_distance_reflect="-1"
			init_angle="${roller_init_angle}"
			no_of_roller="6"
		/>
		<!-- Back rollers -->
		<xacro:roller_macro
			parent="${name}"
			radial_dist="${roller_radial_dist}"
			z_distance="${roller_z_distance}"
			z_distance_reflect="1"
			init_angle="${roller_init_angle}"
			no_of_roller="0"
		/>
		<xacro:roller_macro
			parent="${name}"
			radial_dist="${roller_radial_dist}"
			z_distance="${roller_z_distance}"
			z_distance_reflect="1"
			init_angle="${roller_init_angle}"
			no_of_roller="1"
		/>
		<xacro:roller_macro
			parent="${name}"
			radial_dist="${roller_radial_dist}"
			z_distance="${roller_z_distance}"
			z_distance_reflect="1"
			init_angle="${roller_init_angle}"
			no_of_roller="2"
		/>
		<xacro:roller_macro
			parent="${name}"
			radial_dist="${roller_radial_dist}"
			z_distance="${roller_z_distance}"
			z_distance_reflect="1"
			init_angle="${roller_init_angle}"
			no_of_roller="3"
		/>
		<xacro:roller_macro
			parent="${name}"
			radial_dist="${roller_radial_dist}"
			z_distance="${roller_z_distance}"
			z_distance_reflect="1"
			init_angle="${roller_init_angle}"
			no_of_roller="4"
		/>
		<xacro:roller_macro
			parent="${name}"
			radial_dist="${roller_radial_dist}"
			z_distance="${roller_z_distance}"
			z_distance_reflect="1"
			init_angle="${roller_init_angle}"
			no_of_roller="5"
		/>
		<xacro:roller_macro
			parent="${name}"
			radial_dist="${roller_radial_dist}"
			z_distance="${roller_z_distance}"
			z_distance_reflect="1"
			init_angle="${roller_init_angle}"
			no_of_roller="6"
		/>
		<transmission name="rim_${name}_transmission">

			<type>transmission_interface/SimpleTransmission</type>
			<joint name="rim_${name}_joint">

				<hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>

			</joint>
			<actuator name="rim_${name}_motor">

				<hardwareInterface>EffortJointInterface</hardwareInterface>
				<mechanicalReduction>1</mechanicalReduction>

			</actuator>

		</transmission>

	</xacro:macro>

</robot>
